services:
  - type: web
    name: bool-test-apps
    env: static
    buildCommand: yarn build
    staticPublishPath: dist
    pullRequestPreviewsEnabled: true
    envVars:
      - key: JS_APP_URL
        value: https://e2e.usebool.com/
