services:
  - type: web
    name: bool-test-apps
    env: static
    buildCommand: cd core-js && yarn build
    staticPublishPath: core-js/dist
    pullRequestPreviewsEnabled: true
    envVars:
      - key: JS_APP_URL
        value: https://e2e.usebool.com/
