# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run:
          name: Install yarn
          command: yarn install
      - run:
          name: Install Cypress
          command: npx cypress install
      - run:
          name: Run cypress ffs
          command: yarn e2e:ci

