# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Install npm
          command: npm install
      - run:
          name: Install Cypress
          command: npx cypress install
      - run:
          name: Run cypress ffs
          command: npm e2e:ci

