name: postdeploy

on: [push, deployment_status, workflow_dispatch]

jobs:
  e2e:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2-beta
        with:
          node-version: 16

      - name: Run Cypress
        uses: cypress-io/github-action@v2
        with:
          command: yarn e2e:ci
          env: JS_APP_URL=https://bool-test-apps.onrender.com
          config: video=true,screenshotOnRunFailure=true

      - name: Archive test screenshots
        uses: actions/upload-artifact@v1
        with:
          name: screenshots
          path: cypress/screenshots
        if: ${{ failure() }}

      - name: Archive test videos
        uses: actions/upload-artifact@v1
        with:
          name: videos
          path: cypress/videos
        if: ${{ failure() }}
