name: postdeploy

on: [push, deployment_status, workflow_dispatch]

jobs:
  e2e:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2-beta
        with:
          node-version: 16

      - name: Install modules
        run: yarn

      - name: Run Cypress
        uses: cypress-io/github-action@v2
